spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: search_engine
    password: search_engine
    driver-class-name: org.postgresql.Driver
    connection-pool-size: 5
  main:
    banner-mode: off
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

site-list: https://volochek.life/
          ,https://www.lutherancathedral.ru/
          ,https://www.svetlovka.ru/
          #,https://dimonvideo.ru/
          #,http://www.playback.ru/
          #,https://et-cetera.ru/mobile/
          #,http://radiomv.ru/
          #,https://ipfran.ru/
          #,https://nikoartgallery.com/
          #,https://dombulgakova.ru/

web-interface: /admin
user-agent: XSearchBot

logging:
  level:
    org:
      springframework:
        transaction: OFF
        jdbc:
          core:
            JdbcTemplate: OFF
          StatementCreatorUtils: OFF
      hibernate:
        type: OFF
        SQL: OFF
        engine:
          transaction:
            internal:
              TransactionImpl: OFF
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

