spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: search_engine
    password: search_engine
    driver-class-name: org.postgresql.Driver
    connection-pool-size: 5
  main:
    banner-mode: off
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

site-list: http://www.playback.ru/
          ,https://volochek.life/
          ,http://radiomv.ru/
          ,https://ipfran.ru/
          ,https://dimonvideo.ru/
          ,https://nikoartgallery.com/
          ,https://et-cetera.ru/mobile/
          ,https://www.lutherancathedral.ru/
          ,https://dombulgakova.ru/
          ,https://www.svetlovka.ru/

web-interface: /admin
user-agent: XSearchBot

logging:
  level:
    org:
      hibernate:
        SQL: trace
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
