spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine?rewriteBatchedStatements=true
    username: search_engine
    password: search_engine
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: off

someParameter:
  value: 5463